version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ../backend/
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - backend_static:/backend_static
      - media:/app/media/images
  
  nginx:
    build: ./
    ports:
      - "80:80"
    depends_on:
     #  - frontend
      - backend
    volumes:
      - backend_static:/backend_static
      - media:/media/recipes/images
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # - ../frontend/build:/usr/share/nginx/html/
    #  - ../docs/:/usr/share/nginx/html/api/docs/
      
   
 